USE proyecto1;

-- Creando tablas --
CREATE TABLE IF NOT EXISTS covid_deaths(
iso_code VARCHAR(15),
continent VARCHAR(50),
location VARCHAR(50),
date VARCHAR(30),
population INT,
total_cases INT,
new_cases INT,
new_cases_smoothed FLOAT SIGNED,
total_deaths INT,
new_deaths INT,
new_deaths_smoothed INT,
total_cases_per_million FLOAT SIGNED,
new_cases_per_million FLOAT SIGNED,
new_cases_smoothed_per_million FLOAT SIGNED,
total_deaths_per_million FLOAT SIGNED,
new_deaths_per_million FLOAT SIGNED,
new_deaths_smoothed_per_million FLOAT SIGNED,
reproduction_rate FLOAT SIGNED,
icu_patients FLOAT SIGNED,
icu_patients_per_million FLOAT SIGNED,
hosp_patients FLOAT SIGNED,
hosp_patients_per_million FLOAT SIGNED,
weekly_icu_admissions FLOAT SIGNED,
weekly_icu_admissions_per_million FLOAT SIGNED,
weekly_hosp_admissions FLOAT SIGNED,
weekly_hosp_admissions_per_million FLOAT SIGNED);

CREATE TABLE IF NOT EXISTS covid_vacc(
iso_code VARCHAR(15),
continent VARCHAR(50),
location VARCHAR(50),
date VARCHAR(30),
new_tests INT,
total_tests INT,
total_tests_per_thousand FLOAT SIGNED,
new_tests_per_thousand FLOAT SIGNED,
new_tests_smoothed INT,
new_tests_smoothed_per_thousand FLOAT SIGNED,
positive_rate FLOAT SIGNED,
tests_per_case FLOAT SIGNED,
tests_units VARCHAR(50),
total_vaccinations INT,
people_vaccinated INT,
people_fully_vaccinated INT,
new_vaccinations INT,
new_vaccinations_smoothed INT,
total_vaccinations_per_hundred FLOAT SIGNED,
people_vaccinated_per_hundred FLOAT SIGNED,
people_fully_vaccinated_per_hundred FLOAT SIGNED,
new_vaccinations_smoothed_per_million FLOAT SIGNED,
stringency_index FLOAT SIGNED,
population_density FLOAT SIGNED,
median_age FLOAT SIGNED,
aged_65_older FLOAT SIGNED,
aged_70_older FLOAT SIGNED,
gdp_per_capita FLOAT SIGNED,
extreme_poverty FLOAT SIGNED,
cardiovasc_death_rate FLOAT SIGNED,
diabetes_prevalence FLOAT SIGNED,
female_smokers FLOAT SIGNED,
male_smokers FLOAT SIGNED,
handwashing_facilities FLOAT SIGNED,
hospital_beds_per_thousand FLOAT SIGNED,
life_expectancy FLOAT SIGNED,
human_development_index FLOAT SIGNED);